export default {
  permission: {
    "scope.userLocation": {
      desc: "你的位置信息将用于小程序位置接口的效果展示",
    },
  },
  "pages": [
    "pages/index/index",
    "pages/discover/index",
    "pages/discover/accountBook/index",
    "pages/discover/cardGenerator/index",
    "pages/discover/musicBox/index",
    "pages/profile/index",
    "pages/product/index",
    "pages/login/index",
    "pages/component/index",
    "pages/component/scrollView/index",
    "pages/component/movableView/index",
    "pages/component/webView/index",
    "pages/api/index",
    "pages/api/scanCode/index",
    "pages/api/screenshot/index",
    "pages/api/clipboard/index",
    "pages/api/network/index",
    "pages/api/bluetoothWifi/index",
    "pages/basic/index",
    "pages/container/index",
    "pages/form/index",
    "pages/location/index",
    "pages/map/index",
    "pages/media/index",
    "pages/skyline/index",
    "pages/contact/index",
    "pages/device/index"
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#459405",
    navigationBarTitleText: "WeChat",
    navigationBarTextStyle: "white",
  },
  tabBar: {
    color: "#999",
    selectedColor: "#4594D5",
    backgroundColor: "#fff",
    borderStyle: "black",
    list: [
      {
        pagePath: "pages/index/index",
        text: "首页",
        iconPath: "./assets/tabs/home.png",
        selectedIconPath: "./assets/tabs/home-active.png",
      },
      {
        pagePath: "pages/discover/index",
        text: "发现",
        iconPath: "./assets/tabs/discover.png",
        selectedIconPath: "./assets/tabs/discover-active.png",
      },
      {
        pagePath: "pages/profile/index",
        text: "我的",
        iconPath: "./assets/tabs/profile.png",
        selectedIconPath: "./assets/tabs/profile-active.png",
      },
      {
        pagePath: "pages/component/index",
        text: "组件",
        iconPath: "./assets/tabs/componements.png",
        selectedIconPath: "./assets/tabs/componements-active.png",
      },
      {
        pagePath: "pages/api/index",
        text: "API",
        iconPath: "./assets/tabs/api.png",
        selectedIconPath: "./assets/tabs/api-active.png",
      },
    ],
  },
};
